u=User.new(:login=>"admin", :password=>"admin2", :password_confirmation=>"admin2", :email=>"admin@msiu.ru")
u.role=1
u.save

#факультеты
Faculty.create(:short_name => "ФПМТФ", :name => "Факультет прикладной математики и технической физики")
Faculty.create(:short_name => "АФ", :name => "Автомобильный факультет")
Faculty.create(:short_name => "ЮФ", :name => "Юридический факультет")

#кафедры
Chair.create(:chnum => "7", :chname => "колледж")
Chair.create(:chnum => "11", :chname => "автомобилей и двигателей")
Chair.create(:chnum => "12", :chname => "технологий и металлорежущих систем автомобилестроения")
Chair.create(:chnum => "13", :chname => "машин и технологий обработки металлов давлением")
Chair.create(:chnum => "14", :chname => "литейного производства")
Chair.create(:chnum => "15", :chname => "оборудования и технологий сварочного производства")
Chair.create(:chnum => "16", :chname => "металлообрабатывающих систем с ЧПУ")
Chair.create(:chnum => "21", :chname => "экономики и планирования в организации")
Chair.create(:chnum => "22", :chname => "менеджмента")
Chair.create(:chnum => "23", :chname => "бухгалтерского учета и аудита")
Chair.create(:chnum => "24", :chname => "управления инновационными проектами")
Chair.create(:chnum => "25", :chname => "управления персоналом")
Chair.create(:chnum => "26", :chname => "финансов и кредита")
Chair.create(:chnum => "27", :chname => "государственного управления и экономической безопасности")
Chair.create(:chnum => "28", :chname => "информационной безопасности")
Chair.create(:chnum => "29", :chname => "информационных технологий и систем в экономике и управлении")
Chair.create(:chnum => "31", :chname => "общей и прикладной математики")
Chair.create(:chnum => "32", :chname => "материаловедения и технологии конструкционных материалов")
Chair.create(:chnum => "33", :chname => "автоматики, информатики и систем управления")
Chair.create(:chnum => "34", :chname => "электротехники, теплотехники, гидравлики и энергетических машин")
Chair.create(:chnum => "35", :chname => "технической физики")
Chair.create(:chnum => "36", :chname => "информационных систем и технологий")
Chair.create(:chnum => "37", :chname => "промышленной теплоэнергетики")
Chair.create(:chnum => "41", :chname => "трудового права и права социального обеспечения")
Chair.create(:chnum => "42", :chname => "уголовного права и уголовного процесса")
Chair.create(:chnum => "43", :chname => "истории и теории государства и права и государственного права")
Chair.create(:chnum => "44", :chname => "гражданского права и гражданского процесса")
Chair.create(:chnum => "45", :chname => "административного и финансового права")
Chair.create(:chnum => "51", :chname => "эксплуатации транспортных средств")
Chair.create(:chnum => "52", :chname => "инженерной защиты окружающей среды и рационального использования природных ресурсов")
Chair.create(:chnum => "53", :chname => "профессиональной педагогики и креативного образования")
Chair.create(:chnum => "54", :chname => "бухгалтерского учёта и налогообложения в государственных (муниципальных) учреждениях")
Chair.create(:chnum => "61", :chname => "русского языка и культуры речи")
Chair.create(:chnum => "62", :chname => "инновационных технологий в обучении иностранным языкам")
Chair.create(:chnum => "71", :chname => "менеджмента организации")
Chair.create(:chnum => "72", :chname => "экономики")
Chair.create(:chnum => "73", :chname => "государственно- и гражданско-правовых дисциплин")
Chair.create(:chnum => "74", :chname => "естественно-научных и инженерно-технических дисциплин")
Chair.create(:chnum => "75", :chname => "общих гуманитарных и социальных дициплин")
Chair.create(:chnum => "76", :chname => "управления социально-экономическими процессами")
Chair.create(:chnum => "81", :chname => "военная кафедра")
Chair.create(:chnum => "111", :chname => "графики")
Chair.create(:chnum => "112", :chname => "теоретической механики и теории механизмов")
Chair.create(:chnum => "113", :chname => "сопротивления материалов")
Chair.create(:chnum => "114", :chname => "деталей машин")
Chair.create(:chnum => "115", :chname => "экономики и управления производством")
Chair.create(:chnum => "116", :chname => "безопасности жизнедеятельности и промышленной экологии")
Chair.create(:chnum => "211", :chname => "естественных и технических наук")
Chair.create(:chnum => "212", :chname => "экономической теории")
Chair.create(:chnum => "213", :chname => "математических методов в экономике")
Chair.create(:chnum => "221", :chname => "экономика и менеджмент")
Chair.create(:chnum => "222", :chname => "информационные технологии и системы в экономике и управлении")
Chair.create(:chnum => "223", :chname => "информационная безопасность")
Chair.create(:chnum => "224", :chname => "бухгалтерский учет и аудит")
Chair.create(:chnum => "225", :chname => "математические методы в экономике")
Chair.create(:chnum => "227", :chname => "управление персоналом")
Chair.create(:chnum => "228", :chname => "государственное управление и экономическая безопасность")
Chair.create(:chnum => "311", :chname => "химии")
Chair.create(:chnum => "312", :chname => "физики")
Chair.create(:chnum => "314", :chname => "физического воспитания")
Chair.create(:chnum => "411", :chname => "философии и истории")
Chair.create(:chnum => "412", :chname => "истории и социологии")
Chair.create(:chnum => "413", :chname => "иностранных языков")
Chair.create(:chnum => "666", :chname => "ЦКТ (виртуальная кафедра)")
Chair.create(:chnum => "711", :chname => "Московский индустриальный колледж")
Chair.create(:chnum => "777", :chname => "ИДО (виртуальная кафедра)")
Chair.create(:chnum => "1000", :chname => "Аспирантура")
Chair.create(:chnum => "1001", :chname => "АТХС Отдел безопасности и охраны")
Chair.create(:chnum => "1002", :chname => "АТХС Отдел материально-технического снабжения")
Chair.create(:chnum => "1003", :chname => "АТХС Отдел обеспечения учебного процесса")
Chair.create(:chnum => "1004", :chname => "АТХС Отдел охраны труда")
Chair.create(:chnum => "1004", :chname => "АТХС")
Chair.create(:chnum => "1006", :chname => "АТХС Строительный отдел")
Chair.create(:chnum => "1007", :chname => "Библиотека")
Chair.create(:chnum => "1008", :chname => "Бухгалтерия")
Chair.create(:chnum => "1009", :chname => "Бюро технического обеспечения")
Chair.create(:chnum => "1010", :chname => "Бюро эксплуатации")
Chair.create(:chnum => "1011", :chname => "Высшая школа Лизинга")
Chair.create(:chnum => "1012", :chname => "Деканат автомобильного факультета")
Chair.create(:chnum => "1013", :chname => "Деканат гуманитарного факультета")
Chair.create(:chnum => "1014", :chname => "Деканат факультета ФЭМИТ")
Chair.create(:chnum => "1015", :chname => "Издательский центр")
Chair.create(:chnum => "1016", :chname => "Институт ВТУЗ-ЗИЛ")
Chair.create(:chnum => "1017", :chname => "Институт дистанционного образования")
Chair.create(:chnum => "1018", :chname => "Информационно-аналитический центр")
Chair.create(:chnum => "1019", :chname => "Информационно-вычислительный центр")
Chair.create(:chnum => "1020", :chname => "Коммерческий отдел")
Chair.create(:chnum => "1021", :chname => "Лаборатория Web-дизайна")
Chair.create(:chnum => "1022", :chname => "Лаборатория безопасности жизнедеятельности и пром. экологии")
Chair.create(:chnum => "1023", :chname => "Лаборатория видеосъемки и видеомонтажа")
Chair.create(:chnum => "1024", :chname => "Лаборатория естественных и технических наук")
Chair.create(:chnum => "1025", :chname => "Лаборатория информатики")
Chair.create(:chnum => "1026", :chname => "Лаборатория информационных технологий")
Chair.create(:chnum => "1027", :chname => "Лаборатория кафедры 23 Инженерно-технические средства защиты информации")
Chair.create(:chnum => "1028", :chname => "Лаборатория кафедры 27 Управление персоналом")
Chair.create(:chnum => "1029", :chname => "Лаборатория маркетинга")
Chair.create(:chnum => "1030", :chname => "Лаборатория непрерывного образования")
Chair.create(:chnum => "1031", :chname => "Лаборатория новых обучающих технологий")
Chair.create(:chnum => "1032", :chname => "Лаборатория обеспечения полиграфической деятельности")
Chair.create(:chnum => "1033", :chname => "Лаборатория подготовки макетов")
Chair.create(:chnum => "1034", :chname => "Лаборатория подготовки средств обучения")
Chair.create(:chnum => "1035", :chname => "Лаборатория учебно-методического обеспечения")
Chair.create(:chnum => "1036", :chname => "Лаборатория учета и систематизации средств обучения")
Chair.create(:chnum => "1037", :chname => "Материальный отдел")
Chair.create(:chnum => "1038", :chname => "Межвузовская лаборатория станков с ЧПУ (МЛС)")
Chair.create(:chnum => "1039", :chname => "Межвузовский научно-образовательный центр инженерного творчества")
Chair.create(:chnum => "1040", :chname => "Международный отдел")
Chair.create(:chnum => "1041", :chname => "Межкафедральная лаборатория информатики и технологии программирования")
Chair.create(:chnum => "1042", :chname => "Межкафедральная лаборатория САПР")
Chair.create(:chnum => "1043", :chname => "Межкафедральная лаборатория числового программного управления станками (ЛПУ)")
Chair.create(:chnum => "1044", :chname => "Межкафедральная учебная лаборатория материаловедения в машиностроении")
Chair.create(:chnum => "1045", :chname => "Межкафедральная учебно-методическая лаборатория")
Chair.create(:chnum => "1046", :chname => "Общий отдел")
Chair.create(:chnum => "1047", :chname => "ОППП")
Chair.create(:chnum => "1048", :chname => "Отдел дипломного проектирования")
Chair.create(:chnum => "1049", :chname => "Отдел информационных технологий")
Chair.create(:chnum => "1050", :chname => "Отдел кадров")
Chair.create(:chnum => "1051", :chname => "Отдел капитального строительства")
Chair.create(:chnum => "1052", :chname => "Отдел менеджмента и качества")
Chair.create(:chnum => "1053", :chname => "Отдел мониторинга и контроля качества образовательного процесса")
Chair.create(:chnum => "1054", :chname => "Отдел оперативной полиграфии")
Chair.create(:chnum => "1055", :chname => "Отдел организации учебного процесса")
Chair.create(:chnum => "1056", :chname => "Отдел подготовки статистической отчетности учебно-методической деятельности")
Chair.create(:chnum => "1057", :chname => "Отдел по работе со студентами")
Chair.create(:chnum => "1058", :chname => "Отдел по работе с регионами")
Chair.create(:chnum => "1059", :chname => "Отдел технического и программного обеспечения")
Chair.create(:chnum => "1060", :chname => "Планово-финансовый отдел")
Chair.create(:chnum => "1061", :chname => "Полиграфический центр")
Chair.create(:chnum => "1062", :chname => "Расчетный отдел")
Chair.create(:chnum => "1063", :chname => "Редакционный отдел")
Chair.create(:chnum => "1064", :chname => "Ректорат")
Chair.create(:chnum => "1065", :chname => "Специализированная криминалистическая лаборатория")
Chair.create(:chnum => "1066", :chname => "Специальный отдел")
Chair.create(:chnum => "1067", :chname => "Стипендиальный отдел")
Chair.create(:chnum => "1068", :chname => "Учебно-консультационный центр АВТО")
Chair.create(:chnum => "1069", :chname => "Учебно-консультационный центр повышения квалификации")
Chair.create(:chnum => "1070", :chname => "Учебно-методическое управление")
Chair.create(:chnum => "1071", :chname => "Учебный отдел")
Chair.create(:chnum => "1072", :chname => "Учебный центр по автосервису")
Chair.create(:chnum => "1073", :chname => "Центр продвижения учебно-методических разработок")
Chair.create(:chnum => "1074", :chname => "Юридический отдел")
Chair.create(:chnum => "1075", :chname => "Лаборатория технических средств обучения")
Chair.create(:chnum => "1076", :chname => "АТХС Технический отдел")
Chair.create(:chnum => "1077", :chname => "Мобилизационный отдел")
Chair.create(:chnum => "1078", :chname => "Лаборатория учебно-методического обеспечения (ИДО)")

#аудитории
Room.create(:rname => "Первый корпус", :audience => "1101", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1104", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1105", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1108", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1201", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1201(Р)", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1202", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1202Р", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1209", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1218", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1302", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1304", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1310", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1311", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1313", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1315", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1315(Р)", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1316", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1318", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1401", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1410", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1411", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1415", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1502", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1503", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1508", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1510", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1511", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1511-13", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1513", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1516", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1517", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1701", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1702", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1704", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1706", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1707", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1712", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1714", :rcount_aud => "", :comment => "")
Room.create(:rname => "Первый корпус", :audience => "1М", :rcount_aud => "", :comment => "")
